### ISSUE TITLE
Error with module when executing.

### ISSUE THREAD

**Issue by josharmour** [343max/put-io-sync#3]
node sync.js -d Movies -l /Volumes/Public/Downloads/
module.js:328
    throw err;
    ^

Error: Cannot find module './build/Release/shell'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/josharmour/put-io-sync-master/node_modules/execSync/index.js:30:11)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

**Comment by josharmour** [comment]
I believe that execSync needs to be deprecated per other reports of similar errors on other github projects.
